server:
    port: 8081
logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: INFO
    me.chanjar.weixin: INFO
  path: ./mqlogs
wx:
  mp:
    configs:
      - appId:
        secret:
        token:
        aesKey:


